from_latest_tag = true
ignore_merge_commits = true

[commit_types]
feat = { changelog_title = "Features" }
fix = { changelog_title = "Bug Fixes" }
docs = { changelog_title = "Documentation" }
style = { changelog_title = "Styles" }
refactor = { changelog_title = "Code Refactoring" }
perf = { changelog_title = "Performance Improvements" }
test = { changelog_title = "Tests" }
build = { changelog_title = "Build System" }
ci = { changelog_title = "Continuous Integration" }
chore = { changelog_title = "Chores" }
revert = { changelog_title = "Reverts" }
